(eval-when-compile   
 (require 'color-theme))
(defun color-theme-lyh-deep-blue ()
  "Color theme by Li Yuanheng, created 2013-11-26."
  (interactive)
  (color-theme-install
   '(color-theme-lyh-deep-blue
     ((background-color . "#031633")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "orange")
      (foreground-color . "#FFFbd1")
      (mouse-color . "white"))
     ((ac-fuzzy-cursor-color . "red")
      (browse-kill-ring-current-entry-face . highlight)
      (browse-kill-ring-inserted-item-face . highlight)
      (browse-kill-ring-separator-face . bold)
      (cscope-use-face . t)
      (cua-global-mark-cursor-color . "cyan")
      (cua-normal-cursor-color . "#000000")
      (cua-overwrite-cursor-color . "yellow")
      (cua-read-only-cursor-color . "darkgreen")
      (display-time-mail-face . mode-line)
      (highlight-symbol-foreground-color . "black")
      (hl-line-face . my-hl-line-face)
      (ibuffer-deletion-face . error)
      (ibuffer-filter-group-name-face . bold)
      (ibuffer-marked-face . warning)
      (ibuffer-title-face . font-lock-type-face)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . secondary-selection)
      (org-goto-interface . outline)
      (reftex-bib-author-face . font-lock-keyword-face)
      (reftex-bib-extra-face . font-lock-comment-face)
      (reftex-bib-title-face . font-lock-function-name-face)
      (reftex-bib-year-face . font-lock-comment-face)
      (reftex-cursor-selected-face . highlight)
      (reftex-file-boundary-face . font-lock-comment-face)
      (reftex-index-face . font-lock-constant-face)
      (reftex-index-header-face . font-lock-comment-face)
      (reftex-index-section-face . font-lock-function-name-face)
      (reftex-index-tag-face . font-lock-keyword-face)
      (reftex-label-face . font-lock-constant-face)
      (reftex-mouse-selected-face . secondary-selection)
      (reftex-section-heading-face . font-lock-function-name-face)
      (reftex-select-mark-face . bold)
      (reftex-toc-header-face . font-lock-comment-face)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "#031633" :foreground "#FFFbd1" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 158 :width normal :foundry "unknown" :family "misc-fixed"))))
     (Info-title-1-face ((t (:bold t :weight bold :height 1.728 :family "helv"))))
     (Info-title-2-face ((t (:bold t :weight bold :height 1.44 :family "helv"))))
     (Info-title-3-face ((t (:bold t :weight bold :height 1.2 :family "helv"))))
     (Info-title-4-face ((t (:bold t :weight bold :family "helv"))))
     (ac-candidate-face ((t (:foreground "black" :background "lightgray" :underline "darkgray"))))
     (ac-candidate-mouse-face ((t (:background "white"))))
     (ac-completion-face ((t (:foreground "darkgray" :underline t))))
     (ac-gtags-candidate-face ((t (:underline "darkgray" :background "lightgray" :foreground "navy"))))
     (ac-gtags-selection-face ((t (:foreground "white" :background "navy"))))
     (ac-selection-face ((t (:foreground "white" :background "steelblue"))))
     (ac-yasnippet-candidate-face ((t (:underline "darkgray" :background "sandybrown" :foreground "black"))))
     (ac-yasnippet-selection-face ((t (:foreground "white" :background "coral3"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (:background "black"))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (buffer-menu-buffer-name ((t (:foreground "Yellow"))))
     (buffer-menu-current-buffer ((t (:background "#808000002B2B" :foreground "Cyan"))))
     (buffer-menu-delete-mark ((t (:background "Cyan" :foreground "#808000002B2B"))))
     (buffer-menu-directory-buffer ((t (:background "#525227271919" :foreground "Yellow"))))
     (buffer-menu-file-name ((t (:foreground "#7474FFFF7474"))))
     (buffer-menu-flagged-buffer ((t (:foreground "Cyan"))))
     (buffer-menu-headings ((t (:background "#FFFF9B9BFFFF" :foreground "#00005A5AFFFF"))))
     (buffer-menu-marked-buffer ((t (:underline t))))
     (buffer-menu-mode ((t (:foreground "#FFFF9B9BFFFF"))))
     (buffer-menu-mode-line-flagged ((t (:foreground "Red"))))
     (buffer-menu-mode-line-marked ((t (:foreground "Blue"))))
     (buffer-menu-modified-mark ((t (:foreground "#00007373FFFF"))))
     (buffer-menu-read-only-mark ((t (:foreground "Blue"))))
     (buffer-menu-save-mark ((t (:background "Yellow" :foreground "#00005A5AFFFF"))))
     (buffer-menu-size ((t (:foreground "#7474FFFFFFFF"))))
     (buffer-menu-star-buffer ((t (:foreground "#FFFFFFFF7474"))))
     (buffer-menu-time ((t (:foreground "#74749A9AF7F7"))))
     (buffer-menu-view-mark ((t (:background "#808000002B2B" :foreground "Cyan"))))
     (button ((t (:underline t :foreground "cyan1"))))
     (c-annotation-face ((t (:foreground "gold"))))
     (calendar-today ((t (:underline t))))
     (calendar-today-face ((t (:underline t))))
     (change-log-acknowledgement-face ((t (:italic t :slant italic :foreground "#50a0b0"))))
     (change-log-acknowledgment ((t (:italic t :slant italic :foreground "#50a0b0"))))
     (change-log-conditionals ((t (:foreground "SeaGreen2"))))
     (change-log-conditionals-face ((t (:foreground "SeaGreen2"))))
     (change-log-date ((t (:foreground "burlywood"))))
     (change-log-date-face ((t (:foreground "burlywood"))))
     (change-log-email ((t (:foreground "SeaGreen2"))))
     (change-log-email-face ((t (:foreground "SeaGreen2"))))
     (change-log-file ((t (:bold t :weight bold :foreground "goldenrod"))))
     (change-log-file-face ((t (:bold t :weight bold :foreground "goldenrod"))))
     (change-log-function ((t (:foreground "SeaGreen2"))))
     (change-log-function-face ((t (:foreground "SeaGreen2"))))
     (change-log-list ((t (:bold t :weight bold :foreground "DeepSkyBlue1"))))
     (change-log-list-face ((t (:bold t :weight bold :foreground "DeepSkyBlue1"))))
     (change-log-name ((t (:foreground "gold"))))
     (change-log-name-face ((t (:foreground "gold"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan"))))
     (completions-annotations ((t (:italic t :slant italic))))
     (completions-common-part ((t (:family "misc-fixed" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#FFFbd1" :background "#031633" :stipple nil :height 158))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cscope-file-face ((t (:foreground "yellow"))))
     (cscope-function-face ((t (:foreground "cyan"))))
     (cscope-line-face ((t (:foreground "green"))))
     (cscope-line-number-face ((t (:foreground "red"))))
     (cscope-mouse-face ((t (:background "blue" :foreground "white"))))
     (cua-global-mark ((t (:background "yellow1" :foreground "black"))))
     (cua-rectangle ((t (:background "maroon" :foreground "white"))))
     (cua-rectangle-noselect ((t (:background "dimgray" :foreground "white"))))
     (cursor ((t (:background "orange" :foreground "black"))))
     (cvs-filename-face ((t (:foreground "lightblue"))))
     (cvs-handled-face ((t (:foreground "pink"))))
     (cvs-header-face ((t (:bold t :foreground "lightyellow" :weight bold))))
     (cvs-marked-face ((t (:bold t :foreground "green" :weight bold))))
     (cvs-msg-face ((t (:italic t :slant italic))))
     (cvs-need-action-face ((t (:foreground "orange"))))
     (cvs-unknown-face ((t (:foreground "red"))))
     (diary ((t (:foreground "yellow1"))))
     (diary-face ((t (:foreground "yellow1"))))
     (diff-added ((t (:background "#335533"))))
     (diff-added-face ((t (:background "#335533"))))
     (diff-changed ((t (nil))))
     (diff-changed-face ((t (nil))))
     (diff-context ((t (:foreground "grey70"))))
     (diff-context-face ((t (:foreground "grey70"))))
     (diff-file-header ((t (:bold t :background "grey60" :weight bold))))
     (diff-file-header-face ((t (:bold t :background "grey60" :weight bold))))
     (diff-function ((t (:background "grey45"))))
     (diff-function-face ((t (:background "grey45"))))
     (diff-header ((t (:background "grey45"))))
     (diff-header-face ((t (:background "grey45"))))
     (diff-hunk-header ((t (:background "grey45"))))
     (diff-hunk-header-face ((t (:background "grey45"))))
     (diff-index ((t (:bold t :weight bold :background "grey60"))))
     (diff-index-face ((t (:bold t :weight bold :background "grey60"))))
     (diff-indicator-added ((t (:background "#335533"))))
     (diff-indicator-changed ((t (nil))))
     (diff-indicator-removed ((t (:background "#553333"))))
     (diff-nonexistent ((t (:bold t :weight bold :background "grey60"))))
     (diff-nonexistent-face ((t (:bold t :weight bold :background "grey60"))))
     (diff-refine-added ((t (:background "#22aa22"))))
     (diff-refine-change ((t (:background "#aaaa22"))))
     (diff-refine-removed ((t (:background "#aa2222"))))
     (diff-removed ((t (:background "#553333"))))
     (diff-removed-face ((t (:background "#553333"))))
     (dired-directory ((t (:bold t :weight bold :foreground "goldenrod"))))
     (dired-flagged ((t (:bold t :weight bold :foreground "Pink"))))
     (dired-header ((t (:foreground "CadetBlue1"))))
     (dired-ignored ((t (:foreground "grey70"))))
     (dired-mark ((t (:foreground "gold"))))
     (dired-marked ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (dired-perm-write ((t (:italic t :foreground "#50a0b0" :slant italic))))
     (dired-symlink ((t (:bold t :weight bold :foreground "DeepSkyBlue1"))))
     (dired-warning ((t (:foreground "#FFFD9F"))))
     (ediff-current-diff-A ((t (:background "#553333"))))
     (ediff-current-diff-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-B ((t (:background "#335533"))))
     (ediff-current-diff-C ((t (:background "#888833"))))
     (ediff-even-diff-A ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-B ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-fine-diff-A ((t (:background "#aa2222"))))
     (ediff-fine-diff-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-B ((t (:background "#22aa22"))))
     (ediff-fine-diff-C ((t (:background "#aaaa22"))))
     (ediff-odd-diff-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-Ancestor ((t (:background "gray40" :foreground "cyan3"))))
     (ediff-odd-diff-B ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-C ((t (:background "Grey" :foreground "White"))))
     (eieio-custom-slot-tag-face ((t (:foreground "light blue"))))
     (eldoc-highlight-function-argument ((t (:bold t :weight bold))))
     (error ((t (:bold t :foreground "Pink" :weight bold))))
     (escape-glyph ((t (:foreground "cyan"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fixed-pitch ((t (:family "fixed"))))
     (font-latex-bold-face ((t (:bold t :foreground "OliveDrab" :weight bold))))
     (font-latex-italic-face ((t (:italic t :foreground "OliveDrab" :slant italic))))
     (font-latex-math-face ((t (:foreground "burlywood"))))
     (font-latex-sedate-face ((t (:foreground "LightGray"))))
     (font-latex-string-face ((t (:foreground "LightSalmon"))))
     (font-latex-warning-face ((t (:bold t :foreground "Pink" :weight bold))))
     (font-lock-builtin-face ((t (:foreground "LightCoral"))))
     (font-lock-comment-delimiter-face ((t (:italic t :slant italic :foreground "#50a0b0"))))
     (font-lock-comment-face ((t (:italic t :foreground "#50a0b0" :slant italic))))
     (font-lock-constant-face ((t (:foreground "gold"))))
     (font-lock-doc-face ((t (:foreground "BlanchedAlmond"))))
     (font-lock-doc-string-face ((t (:foreground "BlanchedAlmond"))))
     (font-lock-function-name-face ((t (:bold t :foreground "goldenrod" :weight bold))))
     (font-lock-keyword-face ((t (:bold t :foreground "DeepSkyBlue1" :weight bold))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "gold"))))
     (font-lock-reference-face ((t (:foreground "LightCoral"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "burlywood"))))
     (font-lock-type-face ((t (:foreground "CadetBlue1"))))
     (font-lock-variable-name-face ((t (:foreground "SeaGreen2"))))
     (font-lock-warning-face ((t (:foreground "#FFFD9F"))))
     (fringe ((t (:background "#405060"))))
     (glyphless-char ((t (:height 0.6))))
     (header-line ((t (:background "grey20" :foreground "grey90" :box nil))))
     (help-argument-name ((t (:italic t :slant italic))))
     (hide-ifdef-shadow ((t (:foreground "grey70"))))
     (highlight ((t (:background "darkgreen"))))
     (highlight-symbol-face ((t (:background "gray30"))))
     (hl-line ((t (:background "darkgreen"))))
     (hlt-property-highlight ((t (:background "Navy"))))
     (holiday ((t (:background "chocolate4"))))
     (holiday-face ((t (:background "chocolate4"))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:foreground "#FFFD9F"))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:foreground "red1"))))
     (ido-virtual ((t (:foreground "LightCoral"))))
     (info-header-node ((t (:foreground "DeepSkyBlue1"))))
     (info-header-xref ((t (:bold t :foreground "SeaGreen2" :weight bold))))
     (info-menu-5 ((t (:foreground "wheat"))))
     (info-menu-header ((t (:bold t :weight bold :family "helv"))))
     (info-node ((t (:foreground "DeepSkyBlue1"))))
     (info-xref ((t (:bold t :foreground "SeaGreen2" :weight bold))))
     (isearch ((t (:background "palevioletred2" :foreground "brown4"))))
     (isearch-fail ((t (:background "red4"))))
     (italic ((t (:italic t :slant italic))))
     (lazy-highlight ((t (:background "paleturquoise4"))))
     (linemark-caution-face ((t (:background "yellow4"))))
     (linemark-funny-face ((t (:background "blue3"))))
     (linemark-go-face ((t (:background "green4"))))
     (linemark-stop-face ((t (:background "red3"))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:underline t :foreground "violet"))))
     (linum ((t (:foreground "grey70"))))
     (log-edit-header ((t (:bold t :weight bold :foreground "DeepSkyBlue1"))))
     (log-edit-summary ((t (:bold t :weight bold :foreground "goldenrod"))))
     (log-edit-unknown-header ((t (:italic t :slant italic :foreground "#50a0b0"))))
     (magit-branch ((t (:background "grey20" :foreground "grey90" :box nil))))
     (magit-diff-add ((t (:background "#335533"))))
     (magit-diff-del ((t (:background "#553333"))))
     (magit-diff-file-header ((t (:bold t :weight bold :background "grey60"))))
     (magit-diff-hunk-header ((t (:background "grey45"))))
     (magit-diff-none ((t (:foreground "grey70"))))
     (magit-header ((t (:box nil :foreground "grey90" :background "grey20"))))
     (magit-item-highlight ((t (:background "darkgreen"))))
     (magit-item-mark ((t (:foreground "gray10" :background "yellow"))))
     (magit-log-graph ((t (:foreground "grey80"))))
     (magit-log-head-label-bisect-bad ((t (:background "IndianRed1" :foreground "IndianRed4" :box 1))))
     (magit-log-head-label-bisect-good ((t (:background "light green" :foreground "dark olive green" :box 1))))
     (magit-log-head-label-default ((t (:background "Grey50" :box 1))))
     (magit-log-head-label-local ((t (:background "Grey13" :foreground "LightSkyBlue1" :box 1))))
     (magit-log-head-label-patches ((t (:background "IndianRed1" :foreground "IndianRed4" :box 1))))
     (magit-log-head-label-remote ((t (:background "Grey11" :foreground "DarkSeaGreen2" :box 1))))
     (magit-log-head-label-tags ((t (:background "LemonChiffon1" :foreground "goldenrod4" :box 1))))
     (magit-log-message ((t (nil))))
     (magit-log-sha1 ((t (:foreground "tomato"))))
     (magit-section-title ((t (:background "grey20" :foreground "grey90" :box nil))))
     (magit-whitespace-warning-face ((t (:background "#102e4e"))))
     (match ((t (:background "RoyalBlue3"))))
     (menu ((t (:background "gray" :foreground "black" :family "helvetica"))))
     (minibuffer-prompt ((t (:foreground "cyan"))))
     (mode-line ((t (:background "grey75" :foreground "black" :box (:line-width -1 :style released-button)))))
     (mode-line-buffer-id ((t (:bold t :background "gray" :foreground "black" :box (:line-width 2 :style released-button) :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "grey30" :foreground "grey80" :box (:line-width -1 :color "grey40" :style nil) :weight light))))
     (modeline ((t (:background "gray" :foreground "black" :box (:line-width 2 :style released-button)))))
     (modeline-mousable ((t (:background "gray" :foreground "black" :box (:line-width 2 :style released-button)))))
     (modeline-mousable-minor-mode ((t (:background "gray" :foreground "black" :box (:line-width 2 :style released-button)))))
     (mouse ((t (:background "white"))))
     (my-hl-line-face ((t (:background "#1BFF2EFF4BFF" :inverse-video nil))))
     (next-error ((t (:background "#264956"))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (org-agenda-calendar-event ((t (:family "misc-fixed" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#FFFbd1" :background "#031633" :stipple nil :height 158))))
     (org-agenda-calendar-sexp ((t (:family "misc-fixed" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#FFFbd1" :background "#031633" :stipple nil :height 158))))
     (org-agenda-clocking ((t (:foreground "gray10" :background "yellow"))))
     (org-agenda-column-dateline ((t (:family "misc-fixed" :weight normal :slant normal :underline nil :strike-through nil :background "grey30" :height 158))))
     (org-agenda-current-time ((t (:foreground "LightGoldenrod"))))
     (org-agenda-date ((t (:foreground "LightSkyBlue"))))
     (org-agenda-date-today ((t (:italic t :bold t :foreground "LightSkyBlue" :slant italic :weight bold))))
     (org-agenda-date-weekend ((t (:bold t :foreground "LightSkyBlue" :weight bold))))
     (org-agenda-diary ((t (:family "misc-fixed" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#FFFbd1" :background "#031633" :stipple nil :height 158))))
     (org-agenda-dimmed-todo-face ((t (:foreground "grey50"))))
     (org-agenda-done ((t (:foreground "PaleGreen"))))
     (org-agenda-filter-category ((t (:box (:line-width -1 :style released-button) :foreground "black" :background "grey75"))))
     (org-agenda-filter-tags ((t (:box (:line-width -1 :style released-button) :foreground "black" :background "grey75"))))
     (org-agenda-restriction-lock ((t (:background "skyblue4"))))
     (org-agenda-structure ((t (:foreground "LightSkyBlue"))))
     (org-archived ((t (:foreground "grey70"))))
     (org-block ((t (:foreground "grey70"))))
     (org-block-background ((t (nil))))
     (org-block-begin-line ((t (:italic t :foreground "#50a0b0" :slant italic))))
     (org-block-end-line ((t (:italic t :foreground "#50a0b0" :slant italic))))
     (org-checkbox ((t (:bold t :weight bold))))
     (org-checkbox-statistics-done ((t (:bold t :weight bold :foreground "PaleGreen"))))
     (org-checkbox-statistics-todo ((t (:bold t :weight bold :foreground "Pink"))))
     (org-clock-overlay ((t (:background "SkyBlue4"))))
     (org-code ((t (:foreground "grey70"))))
     (org-column ((t (:background "grey30" :strike-through nil :underline nil :slant normal :weight normal :height 158 :family "misc-fixed"))))
     (org-column-title ((t (:bold t :background "grey30" :underline t :weight bold))))
     (org-date ((t (:foreground "Cyan" :underline t))))
     (org-date-selected ((t (:background "Pink"))))
     (org-default ((t (:family "misc-fixed" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#FFFbd1" :background "#031633" :stipple nil :height 158))))
     (org-document-info ((t (:foreground "pale turquoise"))))
     (org-document-info-keyword ((t (:foreground "grey70"))))
     (org-document-title ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (org-done ((t (:bold t :foreground "PaleGreen" :weight bold))))
     (org-drawer ((t (:foreground "LightSkyBlue"))))
     (org-ellipsis ((t (:foreground "LightGoldenrod" :underline t))))
     (org-footnote ((t (:foreground "Cyan" :underline t))))
     (org-formula ((t (:foreground "chocolate1"))))
     (org-headline-done ((t (:foreground "LightSalmon"))))
     (org-hide ((t (:foreground "black"))))
     (org-latex-and-export-specials ((t (:foreground "burlywood"))))
     (org-level-1 ((t (:bold t :foreground "goldenrod" :weight bold))))
     (org-level-2 ((t (:foreground "SeaGreen2"))))
     (org-level-3 ((t (:bold t :foreground "DeepSkyBlue1" :weight bold))))
     (org-level-4 ((t (:italic t :foreground "#50a0b0" :slant italic))))
     (org-level-5 ((t (:foreground "CadetBlue1"))))
     (org-level-6 ((t (:foreground "gold"))))
     (org-level-7 ((t (:foreground "LightCoral"))))
     (org-level-8 ((t (:foreground "burlywood"))))
     (org-link ((t (:underline t :foreground "cyan1"))))
     (org-list-dt ((t (:bold t :weight bold))))
     (org-meta-line ((t (:italic t :slant italic :foreground "#50a0b0"))))
     (org-mode-line-clock ((t (:box (:line-width -1 :style released-button) :foreground "black" :background "grey75"))))
     (org-mode-line-clock-overrun ((t (:box (:line-width -1 :style released-button) :foreground "black" :background "red"))))
     (org-property-value ((t (nil))))
     (org-quote ((t (:foreground "grey70"))))
     (org-scheduled ((t (:foreground "PaleGreen"))))
     (org-scheduled-previously ((t (:foreground "chocolate1"))))
     (org-scheduled-today ((t (:foreground "PaleGreen"))))
     (org-sexp-date ((t (:foreground "Cyan"))))
     (org-special-keyword ((t (:bold t :weight bold :foreground "DeepSkyBlue1"))))
     (org-table ((t (:foreground "LightSkyBlue"))))
     (org-tag ((t (:bold t :weight bold))))
     (org-target ((t (:underline t))))
     (org-time-grid ((t (:foreground "LightGoldenrod"))))
     (org-todo ((t (:bold t :foreground "Pink" :weight bold))))
     (org-upcoming-deadline ((t (:foreground "chocolate1"))))
     (org-verbatim ((t (:foreground "grey70"))))
     (org-verse ((t (:foreground "grey70"))))
     (org-warning ((t (:foreground "#FFFD9F"))))
     (outline-1 ((t (:bold t :weight bold :foreground "goldenrod"))))
     (outline-2 ((t (:foreground "SeaGreen2"))))
     (outline-3 ((t (:bold t :weight bold :foreground "DeepSkyBlue1"))))
     (outline-4 ((t (:italic t :slant italic :foreground "#50a0b0"))))
     (outline-5 ((t (:foreground "CadetBlue1"))))
     (outline-6 ((t (:foreground "gold"))))
     (outline-7 ((t (:foreground "LightCoral"))))
     (outline-8 ((t (:foreground "burlywood"))))
     (popup-face ((t (:background "lightgray" :foreground "black"))))
     (popup-isearch-match ((t (:background "sky blue"))))
     (popup-menu-face ((t (:foreground "black" :background "lightgray"))))
     (popup-menu-mouse-face ((t (:background "blue" :foreground "white"))))
     (popup-menu-selection-face ((t (:background "steelblue" :foreground "white"))))
     (popup-menu-summary-face ((t (:foreground "dimgray" :background "lightgray"))))
     (popup-mouse-face ((t (:background "white"))))
     (popup-scroll-bar-background-face ((t (:background "gray"))))
     (popup-scroll-bar-foreground-face ((t (:background "black"))))
     (popup-summary-face ((t (:background "lightgray" :foreground "dimgray"))))
     (popup-tip-face ((t (:background "khaki1" :foreground "black"))))
     (pos-tip-temp ((t (nil))))
     (pulse-highlight-face ((t (:background "#AAAA33"))))
     (pulse-highlight-start-face ((t (:background "#AAAA33"))))
     (query-replace ((t (:foreground "brown4" :background "palevioletred2"))))
     (region ((t (:background "#264956"))))
     (scroll-bar ((t (:background "gray" :foreground "#506070"))))
     (secondary-selection ((t (:background "yellow" :foreground "gray10"))))
     (semantic-decoration-on-fileless-includes ((t (:background "#009000"))))
     (semantic-decoration-on-includes ((t (nil))))
     (semantic-decoration-on-private-members-face ((t (:background "#200000"))))
     (semantic-decoration-on-protected-members-face ((t (:background "#000020"))))
     (semantic-decoration-on-unknown-includes ((t (:background "#900000"))))
     (semantic-decoration-on-unparsed-includes ((t (:background "#555500"))))
     (semantic-highlight-edits-face ((t (:background "gray20"))))
     (semantic-highlight-func-current-tag-face ((t (:background "gray20"))))
     (semantic-tag-boundary-face ((t (:overline "cyan"))))
     (semantic-unmatched-syntax-face ((t (:underline "red"))))
     (senator-intangible-face ((t (:foreground "gray75"))))
     (senator-momentary-highlight-face ((t (:background "gray30"))))
     (senator-read-only-face ((t (:background "#664444"))))
     (shadow ((t (:foreground "grey70"))))
     (show-paren-match ((t (:background "steelblue3"))))
     (show-paren-match-face ((t (:background "steelblue3"))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (show-paren-mismatch-face ((t (:background "purple" :foreground "white"))))
     (speedbar-button-face ((t (:foreground "green3"))))
     (speedbar-directory-face ((t (:foreground "light blue"))))
     (speedbar-face ((t (:slant normal :weight normal :height 128 :width normal :foundry "unknown" :family "misc-fixed"))))
     (speedbar-file-face ((t (:foreground "cyan"))))
     (speedbar-highlight-face ((t (:background "sea green"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "yellow"))))
     (srecode-separator-face ((t (:bold t :strike-through t :weight bold))))
     (success ((t (:bold t :foreground "Green1" :weight bold))))
     (svn-log-partner-highlight-face ((t (:bold t :weight bold))))
     (svn-status-blame-highlight-face ((t (:background "darkgreen"))))
     (svn-status-blame-rev-number-face ((t (:foreground "LightGoldenrod"))))
     (svn-status-directory-face ((t (:foreground "lightskyblue1"))))
     (svn-status-filename-face ((t (:foreground "beige"))))
     (svn-status-locked-face ((t (:bold t :foreground "Red" :weight bold))))
     (svn-status-marked-face ((t (:foreground "palegreen2"))))
     (svn-status-marked-popup-face ((t (:foreground "palegreen2"))))
     (svn-status-switched-face ((t (:foreground "Aquamarine"))))
     (svn-status-symlink-face ((t (:foreground "cyan"))))
     (svn-status-update-available-face ((t (:foreground "yellow"))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "#102e4e"))))
     (underline ((t (:underline t))))
     (undo-tree-visualizer-active-branch-face ((t (:bold t :foreground "white" :weight bold))))
     (undo-tree-visualizer-current-face ((t (:foreground "red"))))
     (undo-tree-visualizer-default-face ((t (:foreground "gray"))))
     (undo-tree-visualizer-register-face ((t (:foreground "yellow"))))
     (undo-tree-visualizer-unmodified-face ((t (:foreground "cyan"))))
     (variable-pitch ((t (:family "helv"))))
     (vertical-border ((t (nil))))
     (warning ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (which-func ((t (:foreground "Blue1"))))
     (whitespace-empty ((t (:background "yellow" :foreground "firebrick"))))
     (whitespace-hspace ((t (:background "grey24" :foreground "darkgray"))))
     (whitespace-indentation ((t (:background "yellow" :foreground "firebrick"))))
     (whitespace-line ((t (:background "gray20" :foreground "violet"))))
     (whitespace-newline ((t (:foreground "darkgray" :weight normal))))
     (whitespace-space ((t (:background "grey20" :foreground "darkgray"))))
     (whitespace-space-after-tab ((t (:background "yellow" :foreground "firebrick"))))
     (whitespace-space-before-tab ((t (:background "DarkOrange" :foreground "firebrick"))))
     (whitespace-tab ((t (:background "grey22" :foreground "darkgray"))))
     (whitespace-trailing ((t (:bold t :background "red1" :foreground "yellow" :weight bold))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "dim gray"))))
     (widget-inactive ((t (:foreground "light gray"))))
     (widget-single-line-field ((t (:background "dim gray"))))
     (yas--field-debug-face ((t (nil))))
     (yas-field-highlight-face ((t (:background "#353966")))))))
(add-to-list 'color-themes '(color-theme-lyh-deep-blue  "color-theme-lyh-deep-blue" "Li Yuanheng"))
