(autoload 'mc/mark-next-like-this "multiple-cursors"  "multiple-cursors" t)
(autoload 'mc/mark-previous-like-this "multiple-cursors"  "multiple-cursors" t)
(global-set-key (kbd "C->") 'mc/mark-next-like-this)
(global-set-key (kbd "C-<") 'mc/mark-previous-like-this)
(provide 'init-multiple-cursors)
